BBS/urls.py
from django.conf.urls import url
from django.contrib import admin
from blog import views
from django.views.static import serve
from BBS import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', views.login),
    url(r'^get_valid_img/', views.get_valid_img),
    url(r'^index/', views.index),
    url(r'^reg/', views.reg),

    # media 配置
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class UserInfo(AbstractUser):
    """
    用户信息
    telephone:手机号
    avatar:头像
    create_time:创建时间
    blog:站点
    """
    nid = models.AutoField(primary_key=True)
    telephone = models.CharField(max_length=11, null=True, unique=True)
    avatar = models.FileField(upload_to='avatars/', default="/avatars/default.png")
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    blog = models.OneToOneField(to='Blog', to_field='nid', null=True)

    def __str__(self):
        return self.username


class Blog(models.Model):
    """
    博客信息
    """

    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题', max_length=64)
    site = models.CharField(verbose_name='个人博客后缀', max_length=32, unique=True)
    theme = models.CharField(verbose_name='博客主题', max_length=32)

    def __str__(self):
        return self.title


class Category(models.Model):
    """
    博主个人文章分类表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')

    def __str__(self):
        return self.title


class Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')

    def __str__(self):
        return self.title


class Article(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name='文章标题')
    desc = models.CharField(max_length=255, verbose_name='文章描述')
    create_time = models.DateTimeField(verbose_name='创建时间')
    category = models.ForeignKey(to='Category', to_field='nid', null=True)
    user = models.ForeignKey(verbose_name='作者', to='UserInfo', to_field='nid')
    tags = models.ManyToManyField(
        to="Tag",
        through='Article2Tag',
        through_fields=('article', 'tag'),
    )

    def __str__(self):
        return self.title


class ArticleDetail(models.Model):
    """
    文章详细表
    """
    nid = models.AutoField(primary_key=True)
    content = models.TextField()
    article = models.OneToOneField(to='Article', to_field='nid')


class Article2Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='文章', to="Article", to_field='nid')
    tag = models.ForeignKey(verbose_name='标签', to="Tag", to_field='nid')

    class Meta:
        unique_together = [
            ('article', 'tag'),
        ]

    def __str__(self):
        v = self.article.title + "--" + self.tag.title
        return v


class ArticleUpDown(models.Model):
    """
    点赞表
    联合唯一：不让重复点赞
    """

    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey('UserInfo', null=True)
    article = models.ForeignKey("Article", null=True)
    is_up = models.BooleanField(default=True)

    class Meta:
        unique_together = [
            ('article', 'user'),
        ]


class Comment(models.Model):
    """

    评论表

    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid')
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid')
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    parent_comment = models.ForeignKey('self', null=True)

    def __str__(self):
        return self.content

blog/forms.py
from django import forms
import re
from django.core.exceptions import ValidationError
from django.forms import fields, widgets
from blog.models import UserInfo

# 自定义手机号验证规则
def mobile_validate(value):
    mobile_re = re.compile(r'^(13[0-9]|15[012356789]|17[678]|18[0-9]|14[57])[0-9]{8}$')
    if not mobile_re.match(value):
        raise ValidationError('手机号码格式错误')


class RegForm(forms.Form):
    username = forms.CharField(max_length=10,
                               label="用户名",
                               widget=widgets.TextInput(attrs={"class": "form-control"}))
    password = forms.CharField(min_length=6,
                               label="密码",
                               widget=widgets.PasswordInput(attrs={"class": "form-control"}, render_value=True))
    repeat_pwd = forms.CharField(min_length=6,
                                 label="确认密码",
                                 widget=widgets.PasswordInput(attrs={"class": "form-control"}, render_value=True))
    telephone = fields.CharField(validators=[mobile_validate, ],
                                 label="手机号",
                                 error_messages={"required": "手机号不能为空"},
                                 widget=widgets.TextInput(attrs={"class": "form-control"}))
    email = fields.CharField(label="邮箱",
                             widget=widgets.EmailInput(attrs={"class": "form-control"}))

    def clean_username(self):
        val = self.cleaned_data.get("username")
        ret = UserInfo.objects.filter(username=val)
        if not ret:
            return val
        else:
            raise ValidationError("该用户已存在")

    def clean(self):
        if self.cleaned_data.get("repeat_pwd") == self.cleaned_data.get("password"):
            return self.cleaned_data
        else:
            raise ValidationError("两次输入密码不一致")

templates/index.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <!-- 初始化样式重置 -->
    <link href="https://cdn.bootcss.com/normalize/8.0.1/normalize.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        #article_desc {
            margin-left: -30px;
        }

        #article_below ~ div {
            margin-top: 10px;
        }

    </style>
</head>
<body>
{# 头部导航条 #}
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">博客园</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.username %}
                    <li><a href="#">{{ request.user.username }}</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">注销</a></li>
                            <li><a href="#">修改密码</a></li>
                            <li><a href="#">更换头像</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="#">登陆</a></li>
                    <li><a href="#">注册</a></li>

                {% endif %}

            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">
    <div class="row">
        {# 左侧导航栏   #}
        <div class="col-md-2">
            <div class="panel panel-primary">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>

            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">Panel title</h3>
                </div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>
        {# 中间内容   #}
        <div class="col-md-7">
            <div class="article_list">
                {% for article in article_list %}
                    <div class="article_item"><a href=""><h3>{{ article.title }}</h3></a></div>
                    <div class="row">
                        <div class="col-md-2"><img width="60px" height="60px" src="/media/{{ article.user.avatar }}">
                        </div>
                        <div class="col-md-9" id="article_desc">{{ article.desc }}</div>
                    </div>
                    <div class="row small" id="article_below">
                        <div class="col-md-2"><span><a href="">{{ article.user }}</a></span></div>
                        <div class="col-md-3" id="article_desc"><span>发布于:{{ article.create_time |date:"Y-m-d" }}</span>
                        </div>
                        <div class="col-md-2"><span class="glyphicon glyphicon-comment"></span>评论数({{ article.comment_set.count }})</div>
                        <div class="col-md-2"><span class="glyphicon glyphicon-thumbs-up">赞({{ article.articleupdown_set.count }})</span></div>
                    </div>
                    <hr>
                    {{ article.ArticleUpDown.is_up }}
                {% endfor %}
            </div>

        </div>
        <div class="col-md-3">右侧导航栏</div>
    </div>
</div>


<script src="/static/jquery-3.3.1.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <!-- 初始化样式重置 -->
    <link href="https://cdn.bootcss.com/normalize/8.0.1/normalize.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        .container {
            margin-top: 150px;
        }

        .sub {
            margin-top: 15px;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-offset-4 col-md-4">

            <form action="" method="post">
                <div class="form-group">
                    <label for="user">用户名</label>
                    <input type="text" class="form-control" id="user_id">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">密码</label>
                    <input type="password" class="form-control" id="pwd_id">
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label for="exampleInputPassword1">验证码</label>
                        <input type="text" class="form-control" id="valid_img">
                    </div>
                    <div class="col-md-6" class="form-control">
                        <img height="59" width="160" src="/get_valid_img" id="change_img">
                    </div>
                </div>
                <div class="sub">
                    <button type="button" class="btn btn-default" id="login_btn">提交</button>
                    <span class="error" style="color: red;margin-left: 20px"></span>
                </div>
            </form>

        </div>
    </div>
</div>
{% csrf_token %}
<script src="/static/jquery-3.3.1.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/my_js/login.js">

</script>
</body>
</html>

templates/reg.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <!-- 初始化样式重置 -->
    <link href="https://cdn.bootcss.com/normalize/8.0.1/normalize.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        .container {
            margin-top: 50px;
        }

        #exampleInputFile {
            display: none;
        }

        #header_image {
            height: 40px;
            width: 40px;
            margin-left: 20px;
        }

    </style>

</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-offset-4 col-md-4">
            <form action="" method="post">
                {% csrf_token %}
                {% for foo in form %}
                    <div class="form-group">
                        <label>{{ foo.label }}</label>
                        {{ foo }}<span class="error pull-right"></span>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <label for="exampleInputFile">头像
                        <img src="/static/image/1552037426(1).jpg" id="header_image">
                    </label>
                    <input type="file" id="exampleInputFile">
                </div>
                <input type="button" class="btn btn-default pull-right" value="注册">

            </form>

        </div>
    </div>
</div>
{% csrf_token %}
<script src="/static/jquery-3.3.1.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script>
    $("#exampleInputFile").change(function () {
        var choose_file = $(this)[0].files[0];
        var reader = new FileReader();
        reader.readAsDataURL(choose_file);
        reader.onload = function () {
            $("#header_image").attr("src", reader.result)
        }
    })

    $(".btn-default").click(function () {
        var formData = new FormData
        formData.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());
        formData.append("username", $("#id_username").val());
        formData.append("password", $("#id_password").val());
        formData.append("repeat_pwd", $("#id_repeat_pwd").val());
        formData.append("telephone", $("#id_telephone").val());
        formData.append("email", $("#id_email").val());
        formData.append("header_image", $("#exampleInputFile")[0].files[0]);
        $.ajax({
                url: "",
                type: "post",
                processData: false,
                contentType: false,
                data: formData,
                success: function (data) {
                    if (data.user) {
                        location.href = "/login/"
                    } else {
                        {// 注册失败
                            console.log(data.error_dict);
                            // q清空错误信息
                            $("form span").html("");
                            $("form .form-group").removeClass("has-error")
                            // 加载错误信息
                            $.each(data.error_dict, function (field, error_list) {

                                if (field == "__all__") {
                                    $("#id_repeat_pwd").next().html(error_list[0]).css("color", 'red');
                                    $("#id_repeat_pwd").parent().addClass("has-error")


                                }

                                $("#id_" + field).next().html(error_list[0]).css("color", 'red');
                                $("#id_" + field).parent().addClass("has-error")
                            })


                        }
                    }
                }
            }
        )
    })
</script>
</body>
</html>